// soc_ethond_hps_0_hps_io.v

// This file was auto-generated from altera_hps_io_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 14.0 200 at 2015.11.25.12:59:54

`timescale 1 ps / 1 ps
module soc_ethond_hps_0_hps_io (
		output wire [28:0] gpio_loanio_loanio0_i,     // gpio_loanio.loanio0_i
		input  wire [28:0] gpio_loanio_loanio0_oe,    //            .loanio0_oe
		input  wire [28:0] gpio_loanio_loanio0_o,     //            .loanio0_o
		output wire [28:0] gpio_loanio_loanio1_i,     //            .loanio1_i
		input  wire [28:0] gpio_loanio_loanio1_oe,    //            .loanio1_oe
		input  wire [28:0] gpio_loanio_loanio1_o,     //            .loanio1_o
		output wire [8:0]  gpio_loanio_loanio2_i,     //            .loanio2_i
		input  wire [8:0]  gpio_loanio_loanio2_oe,    //            .loanio2_oe
		input  wire [8:0]  gpio_loanio_loanio2_o,     //            .loanio2_o
		output wire [14:0] mem_a,                     //      memory.mem_a
		output wire [2:0]  mem_ba,                    //            .mem_ba
		output wire        mem_ck,                    //            .mem_ck
		output wire        mem_ck_n,                  //            .mem_ck_n
		output wire        mem_cke,                   //            .mem_cke
		output wire        mem_cs_n,                  //            .mem_cs_n
		output wire        mem_ras_n,                 //            .mem_ras_n
		output wire        mem_cas_n,                 //            .mem_cas_n
		output wire        mem_we_n,                  //            .mem_we_n
		output wire        mem_reset_n,               //            .mem_reset_n
		inout  wire [31:0] mem_dq,                    //            .mem_dq
		inout  wire [3:0]  mem_dqs,                   //            .mem_dqs
		inout  wire [3:0]  mem_dqs_n,                 //            .mem_dqs_n
		output wire        mem_odt,                   //            .mem_odt
		output wire [3:0]  mem_dm,                    //            .mem_dm
		input  wire        oct_rzqin,                 //            .oct_rzqin
		output wire        hps_io_emac1_inst_TX_CLK,  //      hps_io.hps_io_emac1_inst_TX_CLK
		output wire        hps_io_emac1_inst_TXD0,    //            .hps_io_emac1_inst_TXD0
		output wire        hps_io_emac1_inst_TXD1,    //            .hps_io_emac1_inst_TXD1
		output wire        hps_io_emac1_inst_TXD2,    //            .hps_io_emac1_inst_TXD2
		output wire        hps_io_emac1_inst_TXD3,    //            .hps_io_emac1_inst_TXD3
		input  wire        hps_io_emac1_inst_RXD0,    //            .hps_io_emac1_inst_RXD0
		inout  wire        hps_io_emac1_inst_MDIO,    //            .hps_io_emac1_inst_MDIO
		output wire        hps_io_emac1_inst_MDC,     //            .hps_io_emac1_inst_MDC
		input  wire        hps_io_emac1_inst_RX_CTL,  //            .hps_io_emac1_inst_RX_CTL
		output wire        hps_io_emac1_inst_TX_CTL,  //            .hps_io_emac1_inst_TX_CTL
		input  wire        hps_io_emac1_inst_RX_CLK,  //            .hps_io_emac1_inst_RX_CLK
		input  wire        hps_io_emac1_inst_RXD1,    //            .hps_io_emac1_inst_RXD1
		input  wire        hps_io_emac1_inst_RXD2,    //            .hps_io_emac1_inst_RXD2
		input  wire        hps_io_emac1_inst_RXD3,    //            .hps_io_emac1_inst_RXD3
		inout  wire        hps_io_qspi_inst_IO0,      //            .hps_io_qspi_inst_IO0
		inout  wire        hps_io_qspi_inst_IO1,      //            .hps_io_qspi_inst_IO1
		inout  wire        hps_io_qspi_inst_IO2,      //            .hps_io_qspi_inst_IO2
		inout  wire        hps_io_qspi_inst_IO3,      //            .hps_io_qspi_inst_IO3
		output wire        hps_io_qspi_inst_SS0,      //            .hps_io_qspi_inst_SS0
		output wire        hps_io_qspi_inst_CLK,      //            .hps_io_qspi_inst_CLK
		inout  wire        hps_io_sdio_inst_CMD,      //            .hps_io_sdio_inst_CMD
		inout  wire        hps_io_sdio_inst_D0,       //            .hps_io_sdio_inst_D0
		inout  wire        hps_io_sdio_inst_D1,       //            .hps_io_sdio_inst_D1
		output wire        hps_io_sdio_inst_CLK,      //            .hps_io_sdio_inst_CLK
		inout  wire        hps_io_sdio_inst_D2,       //            .hps_io_sdio_inst_D2
		inout  wire        hps_io_sdio_inst_D3,       //            .hps_io_sdio_inst_D3
		inout  wire        hps_io_usb1_inst_D0,       //            .hps_io_usb1_inst_D0
		inout  wire        hps_io_usb1_inst_D1,       //            .hps_io_usb1_inst_D1
		inout  wire        hps_io_usb1_inst_D2,       //            .hps_io_usb1_inst_D2
		inout  wire        hps_io_usb1_inst_D3,       //            .hps_io_usb1_inst_D3
		inout  wire        hps_io_usb1_inst_D4,       //            .hps_io_usb1_inst_D4
		inout  wire        hps_io_usb1_inst_D5,       //            .hps_io_usb1_inst_D5
		inout  wire        hps_io_usb1_inst_D6,       //            .hps_io_usb1_inst_D6
		inout  wire        hps_io_usb1_inst_D7,       //            .hps_io_usb1_inst_D7
		input  wire        hps_io_usb1_inst_CLK,      //            .hps_io_usb1_inst_CLK
		output wire        hps_io_usb1_inst_STP,      //            .hps_io_usb1_inst_STP
		input  wire        hps_io_usb1_inst_DIR,      //            .hps_io_usb1_inst_DIR
		input  wire        hps_io_usb1_inst_NXT,      //            .hps_io_usb1_inst_NXT
		input  wire        hps_io_uart0_inst_RX,      //            .hps_io_uart0_inst_RX
		output wire        hps_io_uart0_inst_TX,      //            .hps_io_uart0_inst_TX
		inout  wire        hps_io_i2c0_inst_SDA,      //            .hps_io_i2c0_inst_SDA
		inout  wire        hps_io_i2c0_inst_SCL,      //            .hps_io_i2c0_inst_SCL
		inout  wire        hps_io_gpio_inst_GPIO09,   //            .hps_io_gpio_inst_GPIO09
		inout  wire        hps_io_gpio_inst_GPIO37,   //            .hps_io_gpio_inst_GPIO37
		inout  wire        hps_io_gpio_inst_GPIO44,   //            .hps_io_gpio_inst_GPIO44
		inout  wire        hps_io_gpio_inst_GPIO48,   //            .hps_io_gpio_inst_GPIO48
		inout  wire        hps_io_gpio_inst_GPIO52,   //            .hps_io_gpio_inst_GPIO52
		inout  wire        hps_io_gpio_inst_GPIO65,   //            .hps_io_gpio_inst_GPIO65
		inout  wire        hps_io_gpio_inst_LOANIO58  //            .hps_io_gpio_inst_LOANIO58
	);

	soc_ethond_hps_0_hps_io_border border (
		.gpio_loanio_loanio0_i     (gpio_loanio_loanio0_i),     // gpio_loanio.loanio0_i
		.gpio_loanio_loanio0_oe    (gpio_loanio_loanio0_oe),    //            .loanio0_oe
		.gpio_loanio_loanio0_o     (gpio_loanio_loanio0_o),     //            .loanio0_o
		.gpio_loanio_loanio1_i     (gpio_loanio_loanio1_i),     //            .loanio1_i
		.gpio_loanio_loanio1_oe    (gpio_loanio_loanio1_oe),    //            .loanio1_oe
		.gpio_loanio_loanio1_o     (gpio_loanio_loanio1_o),     //            .loanio1_o
		.gpio_loanio_loanio2_i     (gpio_loanio_loanio2_i),     //            .loanio2_i
		.gpio_loanio_loanio2_oe    (gpio_loanio_loanio2_oe),    //            .loanio2_oe
		.gpio_loanio_loanio2_o     (gpio_loanio_loanio2_o),     //            .loanio2_o
		.mem_a                     (mem_a),                     //      memory.mem_a
		.mem_ba                    (mem_ba),                    //            .mem_ba
		.mem_ck                    (mem_ck),                    //            .mem_ck
		.mem_ck_n                  (mem_ck_n),                  //            .mem_ck_n
		.mem_cke                   (mem_cke),                   //            .mem_cke
		.mem_cs_n                  (mem_cs_n),                  //            .mem_cs_n
		.mem_ras_n                 (mem_ras_n),                 //            .mem_ras_n
		.mem_cas_n                 (mem_cas_n),                 //            .mem_cas_n
		.mem_we_n                  (mem_we_n),                  //            .mem_we_n
		.mem_reset_n               (mem_reset_n),               //            .mem_reset_n
		.mem_dq                    (mem_dq),                    //            .mem_dq
		.mem_dqs                   (mem_dqs),                   //            .mem_dqs
		.mem_dqs_n                 (mem_dqs_n),                 //            .mem_dqs_n
		.mem_odt                   (mem_odt),                   //            .mem_odt
		.mem_dm                    (mem_dm),                    //            .mem_dm
		.oct_rzqin                 (oct_rzqin),                 //            .oct_rzqin
		.hps_io_emac1_inst_TX_CLK  (hps_io_emac1_inst_TX_CLK),  //      hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_emac1_inst_TXD0    (hps_io_emac1_inst_TXD0),    //            .hps_io_emac1_inst_TXD0
		.hps_io_emac1_inst_TXD1    (hps_io_emac1_inst_TXD1),    //            .hps_io_emac1_inst_TXD1
		.hps_io_emac1_inst_TXD2    (hps_io_emac1_inst_TXD2),    //            .hps_io_emac1_inst_TXD2
		.hps_io_emac1_inst_TXD3    (hps_io_emac1_inst_TXD3),    //            .hps_io_emac1_inst_TXD3
		.hps_io_emac1_inst_RXD0    (hps_io_emac1_inst_RXD0),    //            .hps_io_emac1_inst_RXD0
		.hps_io_emac1_inst_MDIO    (hps_io_emac1_inst_MDIO),    //            .hps_io_emac1_inst_MDIO
		.hps_io_emac1_inst_MDC     (hps_io_emac1_inst_MDC),     //            .hps_io_emac1_inst_MDC
		.hps_io_emac1_inst_RX_CTL  (hps_io_emac1_inst_RX_CTL),  //            .hps_io_emac1_inst_RX_CTL
		.hps_io_emac1_inst_TX_CTL  (hps_io_emac1_inst_TX_CTL),  //            .hps_io_emac1_inst_TX_CTL
		.hps_io_emac1_inst_RX_CLK  (hps_io_emac1_inst_RX_CLK),  //            .hps_io_emac1_inst_RX_CLK
		.hps_io_emac1_inst_RXD1    (hps_io_emac1_inst_RXD1),    //            .hps_io_emac1_inst_RXD1
		.hps_io_emac1_inst_RXD2    (hps_io_emac1_inst_RXD2),    //            .hps_io_emac1_inst_RXD2
		.hps_io_emac1_inst_RXD3    (hps_io_emac1_inst_RXD3),    //            .hps_io_emac1_inst_RXD3
		.hps_io_qspi_inst_IO0      (hps_io_qspi_inst_IO0),      //            .hps_io_qspi_inst_IO0
		.hps_io_qspi_inst_IO1      (hps_io_qspi_inst_IO1),      //            .hps_io_qspi_inst_IO1
		.hps_io_qspi_inst_IO2      (hps_io_qspi_inst_IO2),      //            .hps_io_qspi_inst_IO2
		.hps_io_qspi_inst_IO3      (hps_io_qspi_inst_IO3),      //            .hps_io_qspi_inst_IO3
		.hps_io_qspi_inst_SS0      (hps_io_qspi_inst_SS0),      //            .hps_io_qspi_inst_SS0
		.hps_io_qspi_inst_CLK      (hps_io_qspi_inst_CLK),      //            .hps_io_qspi_inst_CLK
		.hps_io_sdio_inst_CMD      (hps_io_sdio_inst_CMD),      //            .hps_io_sdio_inst_CMD
		.hps_io_sdio_inst_D0       (hps_io_sdio_inst_D0),       //            .hps_io_sdio_inst_D0
		.hps_io_sdio_inst_D1       (hps_io_sdio_inst_D1),       //            .hps_io_sdio_inst_D1
		.hps_io_sdio_inst_CLK      (hps_io_sdio_inst_CLK),      //            .hps_io_sdio_inst_CLK
		.hps_io_sdio_inst_D2       (hps_io_sdio_inst_D2),       //            .hps_io_sdio_inst_D2
		.hps_io_sdio_inst_D3       (hps_io_sdio_inst_D3),       //            .hps_io_sdio_inst_D3
		.hps_io_usb1_inst_D0       (hps_io_usb1_inst_D0),       //            .hps_io_usb1_inst_D0
		.hps_io_usb1_inst_D1       (hps_io_usb1_inst_D1),       //            .hps_io_usb1_inst_D1
		.hps_io_usb1_inst_D2       (hps_io_usb1_inst_D2),       //            .hps_io_usb1_inst_D2
		.hps_io_usb1_inst_D3       (hps_io_usb1_inst_D3),       //            .hps_io_usb1_inst_D3
		.hps_io_usb1_inst_D4       (hps_io_usb1_inst_D4),       //            .hps_io_usb1_inst_D4
		.hps_io_usb1_inst_D5       (hps_io_usb1_inst_D5),       //            .hps_io_usb1_inst_D5
		.hps_io_usb1_inst_D6       (hps_io_usb1_inst_D6),       //            .hps_io_usb1_inst_D6
		.hps_io_usb1_inst_D7       (hps_io_usb1_inst_D7),       //            .hps_io_usb1_inst_D7
		.hps_io_usb1_inst_CLK      (hps_io_usb1_inst_CLK),      //            .hps_io_usb1_inst_CLK
		.hps_io_usb1_inst_STP      (hps_io_usb1_inst_STP),      //            .hps_io_usb1_inst_STP
		.hps_io_usb1_inst_DIR      (hps_io_usb1_inst_DIR),      //            .hps_io_usb1_inst_DIR
		.hps_io_usb1_inst_NXT      (hps_io_usb1_inst_NXT),      //            .hps_io_usb1_inst_NXT
		.hps_io_uart0_inst_RX      (hps_io_uart0_inst_RX),      //            .hps_io_uart0_inst_RX
		.hps_io_uart0_inst_TX      (hps_io_uart0_inst_TX),      //            .hps_io_uart0_inst_TX
		.hps_io_i2c0_inst_SDA      (hps_io_i2c0_inst_SDA),      //            .hps_io_i2c0_inst_SDA
		.hps_io_i2c0_inst_SCL      (hps_io_i2c0_inst_SCL),      //            .hps_io_i2c0_inst_SCL
		.hps_io_gpio_inst_GPIO09   (hps_io_gpio_inst_GPIO09),   //            .hps_io_gpio_inst_GPIO09
		.hps_io_gpio_inst_GPIO37   (hps_io_gpio_inst_GPIO37),   //            .hps_io_gpio_inst_GPIO37
		.hps_io_gpio_inst_GPIO44   (hps_io_gpio_inst_GPIO44),   //            .hps_io_gpio_inst_GPIO44
		.hps_io_gpio_inst_GPIO48   (hps_io_gpio_inst_GPIO48),   //            .hps_io_gpio_inst_GPIO48
		.hps_io_gpio_inst_GPIO52   (hps_io_gpio_inst_GPIO52),   //            .hps_io_gpio_inst_GPIO52
		.hps_io_gpio_inst_GPIO65   (hps_io_gpio_inst_GPIO65),   //            .hps_io_gpio_inst_GPIO65
		.hps_io_gpio_inst_LOANIO58 (hps_io_gpio_inst_LOANIO58)  //            .hps_io_gpio_inst_LOANIO58
	);

endmodule
